name : z-bot-pr-review

on:
  pull_request:
    types : [opened, synchronize, reopened]

permissions:
  pull-requests: write
  content: read

jobs:
  pr-review:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3  
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          openai_api_key: ${{ secrets.OPENAI_TOKEN }}